<?xml version="1.0" encoding="utf-8"?><Database Name="MyFirstDatabase" Class="MFDDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=MyFirstDatabase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyFirstDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="CustomerPurchase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Individuals" Member="Individuals">
    <Type Name="Individual">
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NumSalesPerYr" Member="NumSalesPerYrs">
    <Type Name="NumSalesPerYr">
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumSales" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchases" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="PurchaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateofPurchase" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseAmmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseDesc" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SalesReps" Member="SalesReps">
    <Type Name="SalesRep">
      <Column Name="SalesID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SalesName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TotalSales" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeeklyHoursWorked" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="Char(25)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="S_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="S_Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.temptable" Member="temptables">
    <Type Name="temptable">
      <Column Name="value" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>